name: Windows

on: [push, pull_request]

jobs:
  msvc:

    runs-on: windows-latest

    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\

    steps:
    - uses: actions/checkout@v2
    - name: Build
      shell: cmd
      run: '"%MSBUILD_PATH%\MSBuild.exe" Anubis/Anubis.vcxproj /p:Platform=Win32 /p:Configuration=Release'
